### ISSUE TITLE
Org-roam-server discussion/collaboration

### ISSUE THREAD

**Issue by ThomasFKJorna** [smallstepman/org-roam-render#1]
Hi! This is a bit of an awkward way to get in contact, but I was not able to find any other way of doing so, sorry!

I remember you posting a rather long and eloquent comment on the "State of org-roam v2 support" issue in org-roam-server about which features were missing from org-roam-server and how you would want to have a discussion about that. AFAIK that comment is deleted, either by you or by the maintainer, but since I have email alerts setup I still have it (again, kind of weird/stalkerish, sorry!).

The reason I contacted you was that I fully agree with all of the points you make, and I would be very interested in discussing this further and/or possibly collaborating on a fork/new version of org-roam-server. I really like org-roam-server, but that's mostly because it's the only decent graph visualization option that exists for org-roam, not because it works particularly well. Many a time have I been tempted to switch to Obsidian because of their far superior graph, but I just like emacs/org too much. And this is emacs! We should be able to create something much better ourselves right?

To be honest, I think it's probably better to start from scratch: vis.js is not very well suited for very large graphs, and is unable to accomodate fancier features (3D/VR). I was thinking of using [react-force-graph](https://github.com/vasturiano/react-force-graph/) because it a) seems reasonably fast b) has 2D/3D/VR built in and c) uses React, which is much nicer to work with than the plain JS/JQuery org-roam-server uses.

Actually, I would like to go a little further than simply having a nicer org-roam-server. Ideally we'd have a full-fledged web-interface for org-roam, not just a graph, one that (with the help of React-Native) could even feasibly be turned into an Android/iOS app! I've been really craving a good Android interface to org-roam, but unfortunately it doesn't exist... yet!

So, bit of a rant, but what do you think? Would you be interested in discussing this further? Ideally I would love to collaborate and bring this to live together, as working in a team is much more motivating and I'd maybe actually finish it.

**Comment by smallstepman** [comment]
Hi Thomas! I've deleted my original comment because I was worried it was to far fetched and didn't felt good about it but I'm very happy to see I'm not alone in my thinking. Don't worry about how the communication happen, I'm just glad it's happening ^^

It's actually very, very, very funny you wrote what you wrote and the time you selected could not be better... and here is why: closing in favor of https://github.com/smallstepman/org-roam-server/discussions/3
